import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import style from "./layout.module.scss";
import classNames from "classnames/bind";
const cx = classNames.bind(style);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="kr" data-theme="dark">
      <body className={cx("container")}>
        <header className={cx("header")}>
          <div className={cx("header_inner")}></div>
        </header>
        <main className={cx("main")}>{children}</main>
        <footer className={cx("footer")}>
          <div className={cx("footer_innner")}></div>
        </footer>
      </body>
    </html>
  );
}
