import "./globals.css";
import type { Metadata } from "next";
import classNames from "classnames/bind";
import style from "./layout.module.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const cx = classNames.bind(style);

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="kr" data-theme="dark">
      <body className={cx("container")}>
        <header className={cx("header")}>
          <div className={cx("header_inner")}>
            <Header />
          </div>
        </header>
        <main className={cx("main")}>{children}</main>
        <footer className={cx("footer")}>
          <div className={cx("footer_innner")}>
            <Footer />
          </div>
        </footer>
      </body>
    </html>
  );
}
